/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.io.IOException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import model.entity.Livro;
import model.entity.Usuario;
import model.service.LivroService;
import model.service.UsuarioService;

/**
 *
 * @author eduardoSena
 */
public class ReservarLivro extends javax.swing.JInternalFrame {
    
    LivroService livroService = new LivroService();
    UsuarioService usuarioService = new UsuarioService();
    
    public ReservarLivro() {
        initComponents();
        
        try { //Importando dados do arquivo contendo os livros cadastradas
            List<Livro> livros = livroService.importarArquivo("src/main/java/files/livros.txt");
        } catch (Exception e) {
            e.printStackTrace();
        }
        
        try {
            List<Usuario> usuarios = usuarioService.importarArquivo("src/main/java/files/usuarios.txt");
        } catch (Exception e) {
            e.printStackTrace();
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jpReservarLivro = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnReservar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtTitulo = new javax.swing.JTextField();
        btnPesquisar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtList = new javax.swing.JList<>();
        jLabel6 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Buscar Livro");

        setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        setClosable(true);
        setPreferredSize(new java.awt.Dimension(736, 515));

        jpReservarLivro.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Reservar Livro");

        btnReservar.setBackground(new java.awt.Color(0, 0, 0));
        btnReservar.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        btnReservar.setForeground(new java.awt.Color(255, 255, 255));
        btnReservar.setText("Reservar");
        btnReservar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReservarActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Titulo");

        txtTitulo.setBackground(new java.awt.Color(0, 0, 0));
        txtTitulo.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        txtTitulo.setForeground(new java.awt.Color(255, 255, 255));

        btnPesquisar.setBackground(new java.awt.Color(0, 0, 0));
        btnPesquisar.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        btnPesquisar.setForeground(new java.awt.Color(255, 255, 255));
        btnPesquisar.setText("Pesquisar");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        txtList.setBackground(new java.awt.Color(0, 0, 0));
        txtList.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        txtList.setForeground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(txtList);

        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Usuario");

        txtUsuario.setBackground(new java.awt.Color(0, 0, 0));
        txtUsuario.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        txtUsuario.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jpReservarLivroLayout = new javax.swing.GroupLayout(jpReservarLivro);
        jpReservarLivro.setLayout(jpReservarLivroLayout);
        jpReservarLivroLayout.setHorizontalGroup(
            jpReservarLivroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpReservarLivroLayout.createSequentialGroup()
                .addContainerGap(453, Short.MAX_VALUE)
                .addComponent(btnReservar)
                .addContainerGap(194, Short.MAX_VALUE))
            .addGroup(jpReservarLivroLayout.createSequentialGroup()
                .addGap(151, 151, 151)
                .addGroup(jpReservarLivroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jpReservarLivroLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jpReservarLivroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jpReservarLivroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtTitulo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnPesquisar)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jpReservarLivroLayout.createSequentialGroup()
                .addGap(288, 288, 288)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpReservarLivroLayout.setVerticalGroup(
            jpReservarLivroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpReservarLivroLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel2)
                .addGap(39, 39, 39)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPesquisar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnReservar)
                .addContainerGap(112, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpReservarLivro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpReservarLivro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnReservarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReservarActionPerformed
        boolean statusLiv = false; //verificação de não encontrar livro
        boolean statusLiv2 = false; //verificação de encontrar livro
        boolean statusUser = false; //verificação de não encontrar usuario
        boolean statusUser2 = false; //verificação de encontrar usuario
        List<Livro> livros = livroService.listarLivro();
        List<Usuario> usuarios = usuarioService.listarUsuario();
        DefaultListModel dlm = new DefaultListModel();
        
        //Nome do titulo selecionado separado para uso
        String[] sepTitulo = txtList.getSelectedValue().split(" /");
        String titulo = sepTitulo[0];
        
        for (Livro livro : livros) {
            if(titulo.equals(livro.getTitulo())){
                if (livro.getQuantidade() <= 1){
                    JOptionPane.showMessageDialog(null, "Livro " + livro.getTitulo() + " não pode ser reservado!");
                    statusLiv2 = true;
                    break;
                }
                for (Usuario usuario : usuarios) {
                    if (usuario.getLogin().equals(txtUsuario.getText()) && usuario.getTipo().equals("Interno")){
                        livroService.alugarLivro(livro.getTitulo());
                        try {
                            livroService.exportarLivro(livros);
                        } catch (IOException ex) {
                            Logger.getLogger(AlugarLivro.class.getName()).log(Level.SEVERE, null, ex);
                        }
                        JOptionPane.showMessageDialog(null, "•  Reservado com sucesso  •"
                                + "\n- Livro: " + livro.getTitulo()
                                + "\n- Aluno: " + usuario.getNome());
                        statusUser2 = true;
                        statusLiv2 = true;
                        break;
                    }
                    if (usuario.getLogin().equals(txtUsuario.getText()) && usuario.getTipo().equals("Professor")){
                        livroService.alugarLivro(livro.getTitulo());
                        try {
                            livroService.exportarLivro(livros);
                        } catch (IOException ex) {
                            Logger.getLogger(AlugarLivro.class.getName()).log(Level.SEVERE, null, ex);
                        }
                        JOptionPane.showMessageDialog(null, "•  Reservado com sucesso  •"
                                + "\n- Livro: " + livro.getTitulo()
                                + "\n- Professor: " + usuario.getNome());
                        statusUser2 = true;
                        statusLiv2 = true;
                        break;
                    } 
                    if (usuario.getLogin().equals(txtUsuario.getText()) && usuario.getTipo().equals("Externo")){
                        livroService.alugarLivro(livro.getTitulo());
                        try {
                            livroService.exportarLivro(livros);
                        } catch (IOException ex) {
                            Logger.getLogger(AlugarLivro.class.getName()).log(Level.SEVERE, null, ex);
                        }
                        JOptionPane.showMessageDialog(null, "•  Reservado com sucesso  •"
                                + "\n- Livro: " + livro.getTitulo()
                                + "\n- Usuário externo: " + usuario.getNome());
                        statusUser2 = true;
                        statusLiv2 = true;
                        break;
                    } 
                    if (usuario.getLogin().equals(txtUsuario.getText()) == false){
                        
                        statusUser = true;
                        statusLiv2 = true;
                    }
                }
            break;
            } else if (titulo.equals(livro.getTitulo()) == false){
                statusLiv = true;
            }  
        }
        if (statusUser == true && statusUser2 == false) {
            JOptionPane.showMessageDialog(null, "Usuario inválido!");
        }
        if (statusLiv == true && statusLiv2 == false) {
            JOptionPane.showMessageDialog(null, "Livro não encontrado!");
        }
        dlm.clear();
        txtList.setModel(dlm);
        txtUsuario.setText("");
        
    }//GEN-LAST:event_btnReservarActionPerformed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        boolean status = false; //verificação de não encontrar livro
        boolean status2 = false; //verificação de encontrar livro
        List<Livro> livros = livroService.listarLivro();
        List<Usuario> usuarios = usuarioService.listarUsuario();
        String nomeLivro = livroService.nomeTitle(txtTitulo.getText());
        DefaultListModel dlm = new DefaultListModel();

        for (Livro livro : livros) {
            if (nomeLivro.equals(livro.getTitulo())){
                dlm.addElement(livro.getTitulo()+" / Autor: " + livro.getAutor()
                    + " / Ano: " + livro.getAno());

                status2 = true;
            } else if (nomeLivro.equals(livro.getTitulo())){
                status = true;
            }
            txtList.setModel(dlm);
        }
        if (status == true && status2 == false) {
            JOptionPane.showMessageDialog(null, "Livro não encontrado");
        }
        txtTitulo.setText("");

    }//GEN-LAST:event_btnPesquisarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton btnReservar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel jpReservarLivro;
    private javax.swing.JList<String> txtList;
    private javax.swing.JTextField txtTitulo;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
